spring:
  application:
    name: wikimedia-stream-consumer
  kafka:
    admin:
      auto-create: false
    bootstrap-servers: localhost:9092
    consumer:
      group-id: wikimedia-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update